// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyxB6O1frJGGDACRyr7DDfkNgg-sw2SWg',
    appId: '1:931937117097:web:7ba46d216b361d18779ab8',
    messagingSenderId: '931937117097',
    projectId: 'gdsc-solution-challenge-5f038',
    authDomain: 'gdsc-solution-challenge-5f038.firebaseapp.com',
    storageBucket: 'gdsc-solution-challenge-5f038.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs6bxm1MgLO1rybW_CdCeumPCH8UgQ_l8',
    appId: '1:931937117097:android:42aa65c9f762a76e779ab8',
    messagingSenderId: '931937117097',
    projectId: 'gdsc-solution-challenge-5f038',
    storageBucket: 'gdsc-solution-challenge-5f038.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZDWg0sl5k9w6LmqDKQxlgg67xjBwLrjM',
    appId: '1:931937117097:ios:2896c0385691c835779ab8',
    messagingSenderId: '931937117097',
    projectId: 'gdsc-solution-challenge-5f038',
    storageBucket: 'gdsc-solution-challenge-5f038.appspot.com',
    iosBundleId: 'com.example.solutionChallege',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZDWg0sl5k9w6LmqDKQxlgg67xjBwLrjM',
    appId: '1:931937117097:ios:c2769cc59e630eea779ab8',
    messagingSenderId: '931937117097',
    projectId: 'gdsc-solution-challenge-5f038',
    storageBucket: 'gdsc-solution-challenge-5f038.appspot.com',
    iosBundleId: 'com.example.solutionChallege.RunnerTests',
  );
}
